export const LAGOS_AREAS = [
  // --- ISLAND / SOUTH-EAST ---
  'Ajah',
  'Abijo',
  'Agungi',
  'Awoyaya',
  'Banana Island',
  'Chevron',
  'Epe',
  'Igbo Efon',
  'Ikate',
  'Ikoyi',
  'Ikota',
  'Lafiaji',
  'Lekki Phase 1',
  'Lekki Phase 2',
  'Okun Ajah',
  'Oniru',
  'Orchid',
  'Sangotedo',
  'Victoria Island (VI)',

  // --- MAINLAND CENTRAL ---
  'Akoka',
  'Alagomeji',
  'Allen Avenue (Ikeja)',
  'Anthony Village',
  'Bode Thomas (Surulere)',
  'Ebute Metta',
  'Gbagada Phase 1',
  'Gbagada Phase 2',
  'Ikeja',
  'Ikeja GRA',
  'Ilupeju',
  'Magodo Phase 1',
  'Magodo Phase 2',
  'Maryland',
  'Ogudu',
  'Ogudu GRA',
  'Omole Phase 1',
  'Omole Phase 2',
  'Opebi (Ikeja)',
  'Oregun',
  'Sabo (Yaba)',
  'Surulere',
  'Yaba',

  // --- MAINLAND SUBURBS & OUTER ZONES ---
  'Agege',
  'Akowonjo',
  'Amuwo-Odofin',
  'Badagry',
  'Berger',
  'Egbeda',
  'Festac Town',
  'Ifako-Ijaiye',
  'Ikorodu',
  'Ipaja',
  'Isolo',
  'Mile 2',
  'Ojodu',
  'Ojota',
  'Ojo',
  'Okota',
  'Oshodi',
];